# Generated by Django 2.0.4 on 2018-04-13 18:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20180413_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
